# Demographic Data Analyzer

In this challenge you must analyze demographic data using Pandas. You are given a dataset of demographic data that was extracted from the 1994 Census database.

### Dataset Source

Dua, D. and Graff, C. (2019). UCI Machine Learning Repository. Irvine, CA: University of California, School of Information and Computer Science.

You must use Pandas to answer the following questions:
```bash
- How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)
- What is the average age of men?
- What is the percentage of people who have a Bachelor's degree?
- What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?
- What percentage of people without advanced education make more than 50K?
- What is the minimum number of hours a person works per week?
- What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
- What country has the highest percentage of people that earn >50K and what is that percentage?
- Identify the most popular occupation for those who earn >50K in India.
```

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('adult.data.csv' )

In [ ]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
df.shape

(32561, 15)

In [ ]:
missing_value = df.isnull().sum()

print(missing_value)

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
salary            0
dtype: int64

How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)

In [ ]:
race_count = df['race'].value_counts() # unique counts by race
print(f"{race_count}")

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

What is the average age of men?

In [ ]:
average_age_men = df[df['sex']=='Male']['age'].mean()
print(f"The average age of men: {average_age_men:.1f}")

The average age of men: 39.4

What is the percentage of people who have a Bachelor's degree?

In [ ]:
percentage_bachelors = (df[df['education'] == 'Bachelors'].shape[0]/df.shape[0])*100
print(f"The number of people with bachelors degree: {percentage_bachelors:.1f}%")

The number of people with bachelors degree: 16.4%

What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?

In [ ]:
advanced_degree_holders = ['Bachelors', 'Masters', 'Doctorate']
higher_education = df[df['education'].isin(advanced_degree_holders)] # filters people with advanced degree
higher_education_rich = higher_education[higher_education['salary'] == '>50K'] # checks for people with advanced degree and make more than 50K
higher_education_rich = (higher_education_rich.shape[0] / higher_education.shape[0])*100
print(f"percentage of people with higher education and makes > 50K: {higher_education_rich:.1f}%")

percentage of people with higher education and makes > 50K: 46.5%

What percentage of people without advanced education make more than 50K?

In [ ]:
lower_education= df[~df['education'].isin(advanced_degree_holders)] # filters people without advanced degree
lower_education_rich  = lower_education[lower_education ['salary'] == '>50K'] # people with no advanced degree and make more than 50K
lower_education_rich = (lower_education_rich.shape[0] / lower_education.shape[0])*100
print(f"percentage of people with lower education and makes > 50K: {lower_education_rich:.1f}%")

percentage of people with lower education and makes > 50K: 17.4%

What is the minimum number of hours a person works per week?

In [ ]:
min_work_hours = df['hours-per-week'].min()
print(f"The minimum number of hours a person works per week: {min_work_hours} hr")

The minimum number of hours a person works per week: 1 hr

What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?

In [ ]:
num_min_workers= df[df['hours-per-week'] == min_work_hours] # filter people who works 1 hour per week
df2 = num_min_workers[num_min_workers['salary'] == '>50K'] # filters people who work one hour a week and earns more than 50K
rich_percentage = (df2.shape[0] / num_min_workers.shape[0])*100
print(f"percentage of people who work 1 hr/week and earn more than 50K: {rich_percentage:.1f}%")

percentage of people who work 1 hr/week and earn more than 50K: 10.0%

What country has the highest percentage of people that earn >50K and what is that percentage?

In [ ]:
rich_people = df[df['salary'] == '>50K'] # filter for peoples who makes more than 50K
highest_country_percentage = rich_people.groupby('native-country').size() / df.groupby('native-country').size() * 100  # Group by 'native-country' and calculate the percentage
highest_earning_country = highest_country_percentage.idxmax() # Find the country with the highest percentage of people earning >50K
highest_earning_country_percentage = highest_country_percentage.max()

print(f"the country with high percentage of people earnings: {highest_earning_country}, with: {highest_earning_country_percentage:.1f}%")

the country with high percentage of people earnings: Iran, with: 41.9%

Identify the most popular occupation for those who earn >50K in India.

In [ ]:
rich_people_india = rich_people[rich_people['native-country'] == 'India']
occupation_group_india = rich_people_india.groupby('occupation').size()
top_IN_occupation = occupation_group_india.idxmax()


print(f"popular occupation in India who earns > 50K/year: {top_IN_occupation}")

popular occupation in India who earns > 50K/year: Prof-specialty

In [ ]:
# function to pass the unittest

import pandas as pd


def calculate_demographic_data(print_data=True):
    # Read data from file
    df = pd.read_csv('adult.data.csv' )

    # How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
    race_count = df['race'].value_counts() # returns unique counts by race


    # What is the average age of men?
    average_age_men = round(df[df['sex']=='Male']['age'].mean(), 1)


    # What is the percentage of people who have a Bachelor's degree?
    percentage_bachelors = round((df[df['education'] == 'Bachelors'].shape[0]/df.shape[0])*100, 1)

    # What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
    higher_education_holders = ['Bachelors', 'Masters', 'Doctorate']
    higher_education = df[df['education'].isin(higher_education_holders)] # filters people with advanced degree
    higher_education_rich = higher_education[higher_education['salary'] == '>50K'] # checks for people with advanced degree and make more than 50K
    higher_education_rich = round((higher_education_rich.shape[0] / higher_education.shape[0])*100,1)

    # What percentage of people without advanced education make more than 50K?
    lower_education= df[~df['education'].isin(higher_education_holders)] # filters people without advanced degree
    lower_education_rich  = lower_education[lower_education ['salary'] == '>50K'] # people with no advanced degree and make more than 50K
    lower_education_rich = round((lower_education_rich.shape[0] / lower_education.shape[0])*100, 1)

    # What is the minimum number of hours a person works per week (hours-per-week feature)?
    min_work_hours = df['hours-per-week'].min()

    # What percentage of the people who work the minimum number of hours per week have a salary of >50K?
    num_min_workers= df[df['hours-per-week'] == min_work_hours] # filter people who works 1 hour per week
    df2 = num_min_workers[num_min_workers['salary'] == '>50K'] # filters people who work one hour a week and earns more than 50K
    rich_percentage = (df2.shape[0] / num_min_workers.shape[0])*100


    # What country has the highest percentage of people that earn >50K?
    rich_people = df[df['salary'] == '>50K'] # filter for peoples who makes more than 50K
    highest_country_percentage = rich_people.groupby('native-country').size() / df.groupby('native-country').size() * 100  # Group by 'native-country' and calculate the percentage
    highest_earning_country = highest_country_percentage.idxmax() # Find the country with the highest percentage of people earning >50K
    highest_earning_country_percentage = round(highest_country_percentage.max(), 1)


    # Identify the most popular occupation for those who earn >50K in India.
    rich_people_india = rich_people[rich_people['native-country'] == 'India']
    occupation_group_india = rich_people_india.groupby('occupation').size()
    top_IN_occupation = occupation_group_india.idxmax()




    # DO NOT MODIFY BELOW THIS LINE

    if print_data:
        print("Number of each race:\n", race_count)
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print(f"Min work time: {min_work_hours} hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupations in India:", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage':
        highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }

In [ ]:
# run the unittest after uploading the test_module
!python -m unittest test_module.py

..........
----------------------------------------------------------------------
Ran 10 tests in 0.184s

OK